{% set name = "docplex" %}
{% set version = "2.32.257" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/docplex-{{ version }}.tar.gz
  sha256: 0eaf4cb400d7a1c1d6e398a5f2c46268b3d3005e42b6fceb1ac69544dd80277a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - six

test:
  imports:
    - docplex
    - docplex.cp
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.ibm.com/cloud/decision-optimization-for-watson-studio
  summary: The IBM Decision Optimization CPLEX Modeling for Python
  license: Apache-2.0
  license_file: LICENSE.txt
  doc_url: http://ibmdecisionoptimization.github.io/docplex-doc/

extra:
  recipe-maintainers:
    - BastianZim
