{% set name = "docplex" %}
{% set version = "2.23.222" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/docplex-{{ version }}.tar.gz
  sha256: 7395e97c41939288e0ce4f804c7092cf3874e33784549104281a7e94f7d2fb1e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - six

test:
  imports:
    - docplex
    - docplex.cp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.ibm.com/cloud/decision-optimization-for-watson-studio
  summary: The IBM Decision Optimization CPLEX Modeling for Python
  license: Apache-2.0
  license_file: LICENSE.txt
  doc_url: http://ibmdecisionoptimization.github.io/docplex-doc/

extra:
  recipe-maintainers:
    - BastianZim
