{% set name = "docplex" %}
{% set version = "2.30.251" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/docplex-{{ version }}.tar.gz
  sha256: 6503219f5b51275a7e4e77ca4332903b0f80925d205030a48d3f6aa7ca0dbf2a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - six

test:
  imports:
    - docplex
    - docplex.cp
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.ibm.com/cloud/decision-optimization-for-watson-studio
  summary: The IBM Decision Optimization CPLEX Modeling for Python
  license: Apache-2.0
  license_file: LICENSE.txt
  doc_url: http://ibmdecisionoptimization.github.io/docplex-doc/

extra:
  recipe-maintainers:
    - BastianZim
